// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkubwrtneoraktuwopuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrdWJ3cnRuZW9yYWt0dXdvcHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDA4NjMsImV4cCI6MjA2NTkxNjg2M30.rn45kaOoY5M3hgACfMoJhiyLWXqbuGnPmIqG7UC9LDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);