// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbbqnjskpfwnsjzkjuoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiYnFuanNrcGZ3bnNqemtqdW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NzYwNjIsImV4cCI6MjA4NzE1MjA2Mn0.j1adbXz-VKfAocYo30wcrnxIwoAEuNW_6om4JKTQ2Tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
